// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuMgM4jDirFaD4XrHwkCr43YimkKuuqtk',
    appId: '1:979104093342:web:01692d93fee87d6236d78f',
    messagingSenderId: '979104093342',
    projectId: 'gen-lang-client-0883365972',
    authDomain: 'gen-lang-client-0883365972.firebaseapp.com',
    storageBucket: 'gen-lang-client-0883365972.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2xSyuC56p4BKyuO0O217lkDqjRmdeZg8',
    appId: '1:979104093342:android:382746f1ebe97fb836d78f',
    messagingSenderId: '979104093342',
    projectId: 'gen-lang-client-0883365972',
    storageBucket: 'gen-lang-client-0883365972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm0VtzY8LSSSdJdGaNJ3Y2HR-NWqRScaM',
    appId: '1:979104093342:ios:6c8b813af1defc7336d78f',
    messagingSenderId: '979104093342',
    projectId: 'gen-lang-client-0883365972',
    storageBucket: 'gen-lang-client-0883365972.firebasestorage.app',
    iosClientId: '979104093342-ie4iatas98tjdlftbb06iu2is00u4iok.apps.googleusercontent.com',
    iosBundleId: 'com.example.skincareFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm0VtzY8LSSSdJdGaNJ3Y2HR-NWqRScaM',
    appId: '1:979104093342:ios:6c8b813af1defc7336d78f',
    messagingSenderId: '979104093342',
    projectId: 'gen-lang-client-0883365972',
    storageBucket: 'gen-lang-client-0883365972.firebasestorage.app',
    iosClientId: '979104093342-ie4iatas98tjdlftbb06iu2is00u4iok.apps.googleusercontent.com',
    iosBundleId: 'com.example.skincareFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuMgM4jDirFaD4XrHwkCr43YimkKuuqtk',
    appId: '1:979104093342:web:2014dd134a3edb5036d78f',
    messagingSenderId: '979104093342',
    projectId: 'gen-lang-client-0883365972',
    authDomain: 'gen-lang-client-0883365972.firebaseapp.com',
    storageBucket: 'gen-lang-client-0883365972.firebasestorage.app',
  );
}
